name: SBOM generation with Grype
on: 
  workflow_dispatch
jobs:
  create-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of repo
        uses: actions/checkout@v6.0.2
      - name: Setup Java
        uses: actions/setup-java@v5.2.0
        with:
          distribution: temurin
          java-version: 8
          cache: maven
      
      - name: Build Maven project
        run: mvn -B clean package -DskipTest

      - name: Generate SBOM using Syft Action
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: cyclonedx-json
          output-file: dvja-sbom.json

      - name: Install Grype
        run:  
         curl -sSfL https://get.anchore.io/grype | sudo sh -s -- -b /usr/local/bin

      - name: Run SCA scan with Grype
        run:
          grype sbom:./dvja-sbom.json
          
      - name: Upload Grype Report
        uses: actions/upload-artifact@v4
        with:
          name: grype-scan-report
          path: grype-report.json

      - name: Install Snyk
        run:
          npm install -g snyk

      - name: Run SAST scan with Snyk
        env:
          SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}
        run:
         snyk test > sast-report.json

      - name: Upload SAST report
        uses: actions/upload-artifact@v4
        with:
          name: sast-report
          path: sast-report.json
        

          
        

    
